package factura;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author david
 */
public class datos extends javax.swing.JFrame {

    /**
     * Creates new form datos
     */
    public datos() {

        initComponents();
        panel1.setVisible(false);
        ((AbstractDocument) consumoTotal.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        ((AbstractDocument) precioTotal.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        ((AbstractDocument) consumoVane.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        ((AbstractDocument) potenciaTotal.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        ((AbstractDocument) impuestoElect.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        ((AbstractDocument) bonoSocial.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        ((AbstractDocument) alquiler.getDocument()).setDocumentFilter(new NumericDocumentFilter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        consumoTotal = new javax.swing.JTextField();
        precioTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        consumoVane = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        potenciaTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        impuestoElect = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bonoSocial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        alquiler = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        test = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblConsumoTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPrecioTotal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTotalMasIva = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setText("Consumo total: ");

        consumoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumoTotalActionPerformed(evt);
            }
        });

        precioTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTotalActionPerformed(evt);
            }
        });

        jLabel2.setText("Precio total: ");

        consumoVane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumoVaneActionPerformed(evt);
            }
        });

        jLabel3.setText("Consumo Vanesa: ");

        potenciaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaTotalActionPerformed(evt);
            }
        });

        jLabel4.setText("Potencia total: ");

        impuestoElect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impuestoElectActionPerformed(evt);
            }
        });

        jLabel6.setText("Impuesto electricidad:");

        bonoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonoSocialActionPerformed(evt);
            }
        });

        jLabel7.setText("Bono social:");

        alquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alquilerActionPerformed(evt);
            }
        });

        jLabel8.setText("Alquiler:");

        calcular.setText("CALCULAR");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(51, 51, 255));
        jLabel9.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("RESUMEN");
        jLabel9.setOpaque(true);

        jLabel5.setText("Consumo total:");

        lblConsumoTotal.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblConsumoTotal.setText("jLabel10");

        jLabel11.setText("Precio total:");

        lblPrecioTotal.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblPrecioTotal.setText("jLabel12");

        jLabel13.setText("IVA:");

        lblIva.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblIva.setText("jLabel14");

        jLabel15.setText("TOTAL:");

        lblTotalMasIva.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblTotalMasIva.setText("jLabel16");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConsumoTotal)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrecioTotal)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIva)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalMasIva)
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblConsumoTotal)
                    .addComponent(jLabel11)
                    .addComponent(lblPrecioTotal)
                    .addComponent(jLabel13)
                    .addComponent(lblIva)
                    .addComponent(jLabel15)
                    .addComponent(lblTotalMasIva))
                .addContainerGap(544, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(test)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(precioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(consumoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(consumoVane, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(potenciaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(impuestoElect, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bonoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(test)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(impuestoElect, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(bonoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(alquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(calcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(consumoVane, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(potenciaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(consumoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<JTextField> listadoText = new ArrayList<>();


    private void consumoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumoTotalActionPerformed

    }//GEN-LAST:event_consumoTotalActionPerformed

    private void precioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTotalActionPerformed

    private void consumoVaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumoVaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consumoVaneActionPerformed

    private void potenciaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potenciaTotalActionPerformed

    private void impuestoElectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impuestoElectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_impuestoElectActionPerformed

    private void bonoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bonoSocialActionPerformed

    private void alquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alquilerActionPerformed

    public static float pasofloat(String text){
        return Float.parseFloat(text);
    }
    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed

        boolean check = false;
        int cont = 0;

        listadoText.add(consumoTotal);
        listadoText.add(consumoVane);
        listadoText.add(potenciaTotal);
        listadoText.add(precioTotal);
        listadoText.add(impuestoElect);
        listadoText.add(bonoSocial);
        listadoText.add(alquiler);

        Iterator<JTextField> it = listadoText.iterator();

        while (it.hasNext()) {
            JTextField next = it.next();
            if (next.getText().isEmpty()) {
                next.setBackground(Color.red);
                cont ++;
            } else {
                next.setBackground(Color.white);
            }
        }
        
        
        if(cont == 0){
            panel1.setVisible(true);
        }else{
            panel1.setVisible(false);
        }
        
        float varConsumoTotal = Float.parseFloat(consumoTotal.getText());
        float varPrecioTotal = Float.parseFloat(precioTotal.getText());
        float varPrecioMasIva = varPrecioTotal + (varPrecioTotal * 0.21f);
        
        lblConsumoTotal.setText(String.valueOf(varConsumoTotal));
        lblPrecioTotal.setText(String.valueOf(varPrecioTotal));
        lblIva.setText(String.valueOf(varPrecioTotal * 0.21f));
        lblTotalMasIva.setText(String.valueOf(varPrecioMasIva));
    }//GEN-LAST:event_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alquiler;
    private javax.swing.JTextField bonoSocial;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField consumoTotal;
    private javax.swing.JTextField consumoVane;
    private javax.swing.JTextField impuestoElect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblConsumoTotal;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblTotalMasIva;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField potenciaTotal;
    private javax.swing.JTextField precioTotal;
    private javax.swing.JLabel test;
    // End of variables declaration//GEN-END:variables
}
