package factura;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author david
 */
public class datos extends javax.swing.JFrame {

    /**
     * Creates new form datos
     */
    public datos() {

        initComponents();
        panel1.setVisible(false);
        ((AbstractDocument) consumoTotal.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        ((AbstractDocument) precioTotal.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        ((AbstractDocument) consumoVane.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        ((AbstractDocument) potenciaTotal.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        ((AbstractDocument) impuestoElect.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        ((AbstractDocument) bonoSocial.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        ((AbstractDocument) alquiler.getDocument()).setDocumentFilter(new NumericDocumentFilter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jLabel1 = new JLabel();
        consumoTotal = new JTextField();
        precioTotal = new JTextField();
        jLabel2 = new JLabel();
        consumoVane = new JTextField();
        jLabel3 = new JLabel();
        potenciaTotal = new JTextField();
        jLabel4 = new JLabel();
        impuestoElect = new JTextField();
        jLabel6 = new JLabel();
        bonoSocial = new JTextField();
        jLabel7 = new JLabel();
        alquiler = new JTextField();
        jLabel8 = new JLabel();
        calcular = new JButton();
        test = new JLabel();
        panel1 = new JPanel();
        jLabel9 = new JLabel();
        jLabel5 = new JLabel();
        lblConsumoTotal = new JLabel();
        jLabel11 = new JLabel();
        lblPrecioTotal = new JLabel();
        jLabel13 = new JLabel();
        lblIva = new JLabel();
        jLabel15 = new JLabel();
        lblTotalMasIva = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setCursor(null);
        setResizable(false);
        var contentPane = getContentPane();

        //---- jLabel1 ----
        jLabel1.setText("Consumo total: ");

        //---- consumoTotal ----
        consumoTotal.addActionListener(e -> consumoTotalActionPerformed(e));

        //---- precioTotal ----
        precioTotal.addActionListener(e -> precioTotalActionPerformed(e));

        //---- jLabel2 ----
        jLabel2.setText("Precio total: ");

        //---- consumoVane ----
        consumoVane.addActionListener(e -> consumoVaneActionPerformed(e));

        //---- jLabel3 ----
        jLabel3.setText("Consumo Vanesa: ");

        //---- potenciaTotal ----
        potenciaTotal.addActionListener(e -> potenciaTotalActionPerformed(e));

        //---- jLabel4 ----
        jLabel4.setText("Potencia total: ");

        //---- impuestoElect ----
        impuestoElect.addActionListener(e -> impuestoElectActionPerformed(e));

        //---- jLabel6 ----
        jLabel6.setText("Impuesto electricidad:");

        //---- bonoSocial ----
        bonoSocial.addActionListener(e -> bonoSocialActionPerformed(e));

        //---- jLabel7 ----
        jLabel7.setText("Bono social:");

        //---- alquiler ----
        alquiler.addActionListener(e -> alquilerActionPerformed(e));

        //---- jLabel8 ----
        jLabel8.setText("Alquiler:");

        //---- calcular ----
        calcular.setText("CALCULAR");
        calcular.addActionListener(e -> calcularActionPerformed(e));

        //======== panel1 ========
        {
            panel1.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder(new javax.swing.border
            .EmptyBorder(0,0,0,0), "JF\u006frmDesi\u0067ner Ev\u0061luatio\u006e",javax.swing.border.TitledBorder.CENTER,javax
            .swing.border.TitledBorder.BOTTOM,new java.awt.Font("Dialo\u0067",java.awt.Font.BOLD,
            12),java.awt.Color.red),panel1. getBorder()));panel1. addPropertyChangeListener(new java.beans
            .PropertyChangeListener(){@Override public void propertyChange(java.beans.PropertyChangeEvent e){if("borde\u0072".equals(e.
            getPropertyName()))throw new RuntimeException();}});

            //---- jLabel9 ----
            jLabel9.setHorizontalAlignment(SwingConstants.CENTER);
            jLabel9.setText("RESUMEN");
            jLabel9.setOpaque(true);

            //---- jLabel5 ----
            jLabel5.setText("Consumo total:");

            //---- lblConsumoTotal ----
            lblConsumoTotal.setText("jLabel10");

            //---- jLabel11 ----
            jLabel11.setText("Precio total:");

            //---- lblPrecioTotal ----
            lblPrecioTotal.setText("jLabel12");

            //---- jLabel13 ----
            jLabel13.setText("IVA:");

            //---- lblIva ----
            lblIva.setText("jLabel14");

            //---- jLabel15 ----
            jLabel15.setText("TOTAL:");

            //---- lblTotalMasIva ----
            lblTotalMasIva.setText("jLabel16");

            GroupLayout panel1Layout = new GroupLayout(panel1);
            panel1.setLayout(panel1Layout);
            panel1Layout.setHorizontalGroup(
                panel1Layout.createParallelGroup()
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup()
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblConsumoTotal)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel11)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecioTotal)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIva)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel15)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalMasIva)
                                .addGap(0, 65, Short.MAX_VALUE))
                            .addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
            );
            panel1Layout.setVerticalGroup(
                panel1Layout.createParallelGroup()
                    .addGroup(GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblConsumoTotal)
                            .addComponent(jLabel11)
                            .addComponent(lblPrecioTotal)
                            .addComponent(jLabel13)
                            .addComponent(lblIva)
                            .addComponent(jLabel15)
                            .addComponent(lblTotalMasIva))
                        .addContainerGap(544, Short.MAX_VALUE))
            );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(test)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE))
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precioTotal, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
                        .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(34, 34, 34)
                            .addComponent(consumoTotal, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
                        .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(consumoVane, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(potenciaTotal, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(impuestoElect, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bonoSocial, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alquiler, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
                        .addComponent(calcular, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE))
                    .addGap(71, 71, 71))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(test)
                    .addGap(43, 43, 43))
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(impuestoElect, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(bonoSocial, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(alquiler, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(201, 201, 201)
                            .addComponent(calcular))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(consumoVane, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(potenciaTotal, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(consumoTotal, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                            .addGap(161, 161, 161)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(precioTotal, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                    .addComponent(panel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<JTextField> listadoText = new ArrayList<>();


    private void consumoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumoTotalActionPerformed

    }//GEN-LAST:event_consumoTotalActionPerformed

    private void precioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTotalActionPerformed

    private void consumoVaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumoVaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consumoVaneActionPerformed

    private void potenciaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potenciaTotalActionPerformed

    private void impuestoElectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impuestoElectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_impuestoElectActionPerformed

    private void bonoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bonoSocialActionPerformed

    private void alquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alquilerActionPerformed

    public static float pasofloat(String text){
        return Float.parseFloat(text);
    }
    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed

        boolean check = false;
        int cont = 0;

        listadoText.add(consumoTotal);
        listadoText.add(consumoVane);
        listadoText.add(potenciaTotal);
        listadoText.add(precioTotal);
        listadoText.add(impuestoElect);
        listadoText.add(bonoSocial);
        listadoText.add(alquiler);

        Iterator<JTextField> it = listadoText.iterator();

        while (it.hasNext()) {
            JTextField next = it.next();
            if (next.getText().isEmpty()) {
                next.setBackground(Color.red);
                cont ++;
            } else {
                next.setBackground(Color.white);
            }
        }
        
        
        if(cont == 0){
            panel1.setVisible(true);
        }else{
            panel1.setVisible(false);
        }
        
        float varConsumoTotal = Float.parseFloat(consumoTotal.getText());
        float varPrecioTotal = Float.parseFloat(precioTotal.getText());
        float varPrecioMasIva = varPrecioTotal + (varPrecioTotal * 0.21f);
        
        lblConsumoTotal.setText(String.valueOf(varConsumoTotal));
        lblPrecioTotal.setText(String.valueOf(varPrecioTotal));
        lblIva.setText(String.valueOf(varPrecioTotal * 0.21f));
        lblTotalMasIva.setText(String.valueOf(varPrecioMasIva));
    }//GEN-LAST:event_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JLabel jLabel1;
    private JTextField consumoTotal;
    private JTextField precioTotal;
    private JLabel jLabel2;
    private JTextField consumoVane;
    private JLabel jLabel3;
    private JTextField potenciaTotal;
    private JLabel jLabel4;
    private JTextField impuestoElect;
    private JLabel jLabel6;
    private JTextField bonoSocial;
    private JLabel jLabel7;
    private JTextField alquiler;
    private JLabel jLabel8;
    private JButton calcular;
    private JLabel test;
    private JPanel panel1;
    private JLabel jLabel9;
    private JLabel jLabel5;
    private JLabel lblConsumoTotal;
    private JLabel jLabel11;
    private JLabel lblPrecioTotal;
    private JLabel jLabel13;
    private JLabel lblIva;
    private JLabel jLabel15;
    private JLabel lblTotalMasIva;
    // End of variables declaration//GEN-END:variables
}
